version: "3.2"
services:
  run:
    image: dowerx/windows-qemu
    build: ./build
    ports:
      - 5900:5900
      - 5801:5801
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - image:/image:ro
      - ./share:/share
    env_file:
      - .env
  install:
    image: dowerx/windows-qemu
    entrypoint: /install.sh
    ports:
      - 5900:5900
      - 5801:5801
    devices:
      - /dev/kvm:/dev/kvm
    volumes:
      - image:/image:rw
      - /home/${USER}/Downloads/Win10_22H2_English_x64v1.iso:/setup.iso:ro
      - ./share:/share
      - ./setup:/setup
    privileged: true
    env_file:
      - .env

volumes:
  image: